name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/staff-service:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/staff-service:latest

    - name: Set up Azure CLI
      uses: azure/cli@v1

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group bestbuy-rg --name bestbuy-aks-cluster
        kubectl apply -f deployment.yaml
