apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff-service
  template:
    metadata:
      labels:
        app: staff-service
    spec:
      containers:
        - name: staff-service
          image: <your-dockerhub-username>/staff-service:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: staff-service
spec:
  selector:
    app: staff-service
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
